version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: pg_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: db_meals_registration
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
